# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import todo_pb2 as todo__pb2


class TodoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getTodo = channel.unary_unary(
                '/Todo/getTodo',
                request_serializer=todo__pb2.GetTodoRequest.SerializeToString,
                response_deserializer=todo__pb2.GetTodoReply.FromString,
                )
        self.getAllTodo = channel.unary_stream(
                '/Todo/getAllTodo',
                request_serializer=todo__pb2.CommonRequest.SerializeToString,
                response_deserializer=todo__pb2.GetTodoReply.FromString,
                )
        self.getCompletedTodo = channel.unary_stream(
                '/Todo/getCompletedTodo',
                request_serializer=todo__pb2.CommonRequest.SerializeToString,
                response_deserializer=todo__pb2.GetTodoReply.FromString,
                )
        self.getUncompletedTodo = channel.unary_stream(
                '/Todo/getUncompletedTodo',
                request_serializer=todo__pb2.CommonRequest.SerializeToString,
                response_deserializer=todo__pb2.GetTodoReply.FromString,
                )
        self.createTodo = channel.unary_unary(
                '/Todo/createTodo',
                request_serializer=todo__pb2.CreateTodoRequest.SerializeToString,
                response_deserializer=todo__pb2.CreateTodoReply.FromString,
                )
        self.updateTodo = channel.unary_unary(
                '/Todo/updateTodo',
                request_serializer=todo__pb2.UpdateTodoRequest.SerializeToString,
                response_deserializer=todo__pb2.GetTodoReply.FromString,
                )
        self.updateCompletion = channel.unary_unary(
                '/Todo/updateCompletion',
                request_serializer=todo__pb2.GetTodoRequest.SerializeToString,
                response_deserializer=todo__pb2.GetTodoReply.FromString,
                )
        self.deleteTodo = channel.unary_unary(
                '/Todo/deleteTodo',
                request_serializer=todo__pb2.GetTodoRequest.SerializeToString,
                response_deserializer=todo__pb2.CommonReply.FromString,
                )
        self.deleteCompletedTodo = channel.unary_unary(
                '/Todo/deleteCompletedTodo',
                request_serializer=todo__pb2.CommonRequest.SerializeToString,
                response_deserializer=todo__pb2.CommonReply.FromString,
                )
        self.deleteUncompletedTodo = channel.unary_unary(
                '/Todo/deleteUncompletedTodo',
                request_serializer=todo__pb2.CommonRequest.SerializeToString,
                response_deserializer=todo__pb2.CommonReply.FromString,
                )


class TodoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getTodo(self, request, context):
        """GET
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAllTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCompletedTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUncompletedTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createTodo(self, request, context):
        """POST
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateTodo(self, request, context):
        """PUT
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateCompletion(self, request, context):
        """PATCH
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteTodo(self, request, context):
        """DELETE
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteCompletedTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteUncompletedTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.getTodo,
                    request_deserializer=todo__pb2.GetTodoRequest.FromString,
                    response_serializer=todo__pb2.GetTodoReply.SerializeToString,
            ),
            'getAllTodo': grpc.unary_stream_rpc_method_handler(
                    servicer.getAllTodo,
                    request_deserializer=todo__pb2.CommonRequest.FromString,
                    response_serializer=todo__pb2.GetTodoReply.SerializeToString,
            ),
            'getCompletedTodo': grpc.unary_stream_rpc_method_handler(
                    servicer.getCompletedTodo,
                    request_deserializer=todo__pb2.CommonRequest.FromString,
                    response_serializer=todo__pb2.GetTodoReply.SerializeToString,
            ),
            'getUncompletedTodo': grpc.unary_stream_rpc_method_handler(
                    servicer.getUncompletedTodo,
                    request_deserializer=todo__pb2.CommonRequest.FromString,
                    response_serializer=todo__pb2.GetTodoReply.SerializeToString,
            ),
            'createTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.createTodo,
                    request_deserializer=todo__pb2.CreateTodoRequest.FromString,
                    response_serializer=todo__pb2.CreateTodoReply.SerializeToString,
            ),
            'updateTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.updateTodo,
                    request_deserializer=todo__pb2.UpdateTodoRequest.FromString,
                    response_serializer=todo__pb2.GetTodoReply.SerializeToString,
            ),
            'updateCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.updateCompletion,
                    request_deserializer=todo__pb2.GetTodoRequest.FromString,
                    response_serializer=todo__pb2.GetTodoReply.SerializeToString,
            ),
            'deleteTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteTodo,
                    request_deserializer=todo__pb2.GetTodoRequest.FromString,
                    response_serializer=todo__pb2.CommonReply.SerializeToString,
            ),
            'deleteCompletedTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteCompletedTodo,
                    request_deserializer=todo__pb2.CommonRequest.FromString,
                    response_serializer=todo__pb2.CommonReply.SerializeToString,
            ),
            'deleteUncompletedTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteUncompletedTodo,
                    request_deserializer=todo__pb2.CommonRequest.FromString,
                    response_serializer=todo__pb2.CommonReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Todo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Todo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Todo/getTodo',
            todo__pb2.GetTodoRequest.SerializeToString,
            todo__pb2.GetTodoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAllTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Todo/getAllTodo',
            todo__pb2.CommonRequest.SerializeToString,
            todo__pb2.GetTodoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getCompletedTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Todo/getCompletedTodo',
            todo__pb2.CommonRequest.SerializeToString,
            todo__pb2.GetTodoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getUncompletedTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Todo/getUncompletedTodo',
            todo__pb2.CommonRequest.SerializeToString,
            todo__pb2.GetTodoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Todo/createTodo',
            todo__pb2.CreateTodoRequest.SerializeToString,
            todo__pb2.CreateTodoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Todo/updateTodo',
            todo__pb2.UpdateTodoRequest.SerializeToString,
            todo__pb2.GetTodoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Todo/updateCompletion',
            todo__pb2.GetTodoRequest.SerializeToString,
            todo__pb2.GetTodoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Todo/deleteTodo',
            todo__pb2.GetTodoRequest.SerializeToString,
            todo__pb2.CommonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteCompletedTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Todo/deleteCompletedTodo',
            todo__pb2.CommonRequest.SerializeToString,
            todo__pb2.CommonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteUncompletedTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Todo/deleteUncompletedTodo',
            todo__pb2.CommonRequest.SerializeToString,
            todo__pb2.CommonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
